/// Dart backend for cddlc.
///
/// Emits a Dart package:
///   <module>-{cbor,json}/
///     pubspec.yaml              ← Dart SDK >=3.0.0, optional cbor runtime
///     lib/<module>.dart         ← classes + encode/decode
///     test/<module>_test.dart   ← package:test roundtrip tests

use cddlc_codegen::{
    to_pascal_case, to_snake_case,
    Backend, CodegenError, CodegenOptions, CodegenOutput, GeneratedFile,
    IndentWriter,
};
use cddlc_ir::{
    AliasDef, ArrayDef, EnumDef, FieldKey, IrModule, MapDef,
    Occurrence, Primitive, StructDef, TypeDef, TypeRef,
};

pub struct DartBackend;

impl Backend for DartBackend {
    fn language_name(&self) -> &str { "Dart" }
    fn file_extension(&self) -> &str { "dart" }

    fn generate(
        &self,
        module: &IrModule,
        opts:   &CodegenOptions,
    ) -> Result<CodegenOutput, CodegenError> {
        let name     = module.name.as_str();
        let fmt_tag  = if opts.is_json() { "json" } else { "cbor" };
        let pkg_name = format!("{}_{}", dart_pkg(name), fmt_tag);
        let lib_name = dart_pkg(name);

        Ok(CodegenOutput {
            files: vec![
                GeneratedFile {
                    path:    format!("{pkg_name}/pubspec.yaml"),
                    content: emit_pubspec(&pkg_name, opts),
                },
                GeneratedFile {
                    path:    format!("{pkg_name}/lib/{lib_name}.dart"),
                    content: emit_source(module, opts),
                },
                GeneratedFile {
                    path:    format!("{pkg_name}/test/{lib_name}_test.dart"),
                    content: emit_tests(module, &lib_name, opts),
                },
            ],
        })
    }
}

// ── pubspec.yaml ──────────────────────────────────────────────────────────────

fn emit_pubspec(pkg_name: &str, opts: &CodegenOptions) -> String {
    let deps = if opts.is_json() {
        String::new()
    } else {
        "\ndependencies:\n  cbor: ^6.3.0\n".to_owned()
    };
    format!(
        "name: {pkg_name}\n\
         description: Generated by cddlc — do not edit.\n\
         version: 0.1.0\n\
         \n\
         environment:\n\
         {ind}sdk: '>=3.0.0 <4.0.0'\n\
         {deps}\n\
         dev_dependencies:\n\
         {ind}test: ^1.24.0\n",
        ind = "  ",
    )
}

// ── Source file ───────────────────────────────────────────────────────────────

fn emit_source(module: &IrModule, opts: &CodegenOptions) -> String {
    let mut w = IndentWriter::new(2);
    w.line("// Generated by cddlc — do not edit.");
    w.blank();

    // Emit imports based on mode and content
    let needs_typed_data = module_uses_bstr(module) || !opts.is_json();
    if opts.is_json() {
        w.line("import 'dart:convert';");
        if needs_typed_data { w.line("import 'dart:typed_data';"); }
    } else {
        w.line("import 'dart:typed_data';");
        w.line("import 'package:cbor/cbor.dart';");
    }
    w.blank();

    for (_, def) in &module.types {
        emit_type(&mut w, module, def, opts);
        w.blank();
    }

    w.finish()
}

fn module_uses_bstr(module: &IrModule) -> bool {
    module.types.values().any(type_uses_bstr)
}

fn type_uses_bstr(def: &TypeDef) -> bool {
    match def {
        TypeDef::Struct(s) => s.fields.iter().any(|f| typeref_uses_bstr(&f.ty)),
        TypeDef::Array(a)  => typeref_uses_bstr(&a.element),
        TypeDef::Alias(a)  => typeref_uses_bstr(&a.ty),
        _                  => false,
    }
}

fn typeref_uses_bstr(tr: &TypeRef) -> bool {
    match tr {
        TypeRef::Primitive(Primitive::Bstr)    => true,
        TypeRef::Tagged(_, inner)              => typeref_uses_bstr(inner),
        TypeRef::Choice(trs)                   => trs.iter().any(typeref_uses_bstr),
        _                                      => false,
    }
}

fn emit_type(w: &mut IndentWriter, module: &IrModule, def: &TypeDef, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => emit_struct(w, module, s, opts),
        TypeDef::Enum(e)   => emit_enum(w, module, e, opts),
        TypeDef::Array(a)  => emit_array(w, a, opts),
        TypeDef::Map(m)    => emit_map(w, m, opts),
        TypeDef::Alias(a)  => emit_alias(w, a, opts),
    }
}

// ── Struct ────────────────────────────────────────────────────────────────────

fn emit_struct(w: &mut IndentWriter, module: &IrModule, s: &StructDef, opts: &CodegenOptions) {
    if let Some(doc) = s.doc.as_deref() { w.line(&format!("/// {doc}")); }
    if s.deprecated { w.line("@Deprecated('deprecated in schema')"); }

    let class_name = to_pascal_case(&s.name);
    w.line(&format!("class {class_name} {{"));
    w.indent();

    for f in &s.fields {
        if let Some(doc) = f.doc.as_deref() { w.line(&format!("/// {doc}")); }
        let dart_type = dart_field_type(&f.ty, &f.occurrence, opts);
        let fname     = dart_field(&f.name);
        w.line(&format!("final {dart_type} {fname};"));
    }
    w.blank();

    // Constructor
    w.line(&format!("const {class_name}({{"));
    w.indent();
    for f in &s.fields {
        let fname = dart_field(&f.name);
        if matches!(f.occurrence, Occurrence::Optional) {
            w.line(&format!("this.{fname},"));
        } else {
            w.line(&format!("required this.{fname},"));
        }
    }
    w.dedent();
    w.line("});");
    w.blank();

    if opts.is_json() {
        emit_struct_from_json(w, module, s, &class_name, opts);
        w.blank();
        emit_struct_to_json(w, module, s, opts);
        w.blank();
        w.line(&format!(
            "static {class_name} decode(String s) => \
             {class_name}.fromJson(jsonDecode(s) as Map<String, dynamic>);"));
        w.line("String encode() => jsonEncode(toJson());");
    } else {
        emit_struct_from_cbor(w, module, s, &class_name, opts);
        w.blank();
        emit_struct_to_cbor(w, module, s, opts);
    }

    w.dedent();
    w.line("}");
}

fn emit_struct_from_json(w: &mut IndentWriter, module: &IrModule, s: &StructDef, class_name: &str, opts: &CodegenOptions) {
    w.line(&format!("factory {class_name}.fromJson(Map<String, dynamic> json) => {class_name}("));
    w.indent();
    for f in &s.fields {
        let fname = dart_field(&f.name);
        let key   = field_key_str(&f.key);
        if matches!(f.occurrence, Occurrence::Optional) {
            let conv = json_from_expr(&f.ty, &format!("json['{key}']"), module, opts);
            w.line(&format!("{fname}: json.containsKey('{key}') ? {conv} : null,"));
        } else if f.occurrence.is_repeated() {
            let item_conv = json_from_expr(&f.ty, "e", module, opts);
            w.line(&format!(
                "{fname}: (json['{key}'] as List).map((e) => {item_conv}).toList(),"));
        } else {
            let conv = json_from_expr(&f.ty, &format!("json['{key}']"), module, opts);
            w.line(&format!("{fname}: {conv},"));
        }
    }
    w.dedent();
    w.line(");");
}

fn emit_struct_to_json(w: &mut IndentWriter, module: &IrModule, s: &StructDef, opts: &CodegenOptions) {
    w.line("Map<String, dynamic> toJson() => {");
    w.indent();
    let fields: Vec<_> = if s.dcbor {
        let mut fs: Vec<_> = s.fields.iter().collect();
        fs.sort_by(|a, b| a.name.cmp(&b.name));
        fs
    } else {
        s.fields.iter().collect()
    };
    for f in &fields {
        let fname = dart_field(&f.name);
        let key   = field_key_str(&f.key);
        if matches!(f.occurrence, Occurrence::Optional) {
            let val = json_to_expr(&f.ty, &format!("{fname}!"), module, opts);
            w.line(&format!("if ({fname} != null) '{key}': {val},"));
        } else if f.occurrence.is_repeated() {
            let item_val = json_to_expr(&f.ty, "e", module, opts);
            if item_val == "e" {
                w.line(&format!("'{key}': {fname},"));
            } else {
                w.line(&format!("'{key}': {fname}.map((e) => {item_val}).toList(),"));
            }
        } else {
            let val = json_to_expr(&f.ty, &fname, module, opts);
            w.line(&format!("'{key}': {val},"));
        }
    }
    w.dedent();
    w.line("};");
}

fn emit_struct_from_cbor(w: &mut IndentWriter, module: &IrModule, s: &StructDef, class_name: &str, opts: &CodegenOptions) {
    w.line(&format!("static {class_name} decode(Uint8List bytes) {{"));
    w.indent();
    w.line("final v = cbor.decode(bytes);");
    if s.tagged.is_some() {
        w.line("final m = (v is CborTag ? v.value : v) as CborMap;");
    } else {
        w.line("final m = v as CborMap;");
    }
    w.line(&format!("return {class_name}._fromCborMap(m);"));
    w.dedent();
    w.line("}");
    w.blank();
    w.line(&format!("factory {class_name}._fromCborMap(CborMap m) => {class_name}("));
    w.indent();
    for f in &s.fields {
        let fname    = dart_field(&f.name);
        let cbor_key = cbor_map_key(&f.key);
        if matches!(f.occurrence, Occurrence::Optional) {
            let conv = cbor_from_expr(&f.ty, &format!("m[{cbor_key}]"), module, opts);
            w.line(&format!("{fname}: m.containsKey({cbor_key}) ? {conv} : null,"));
        } else if f.occurrence.is_repeated() {
            let item_conv = cbor_from_expr(&f.ty, "e", module, opts);
            w.line(&format!(
                "{fname}: (m[{cbor_key}] as CborList).map((e) => {item_conv}).toList(),"));
        } else {
            let conv = cbor_from_expr(&f.ty, &format!("m[{cbor_key}]!"), module, opts);
            w.line(&format!("{fname}: {conv},"));
        }
    }
    w.dedent();
    w.line(");");
}

fn emit_struct_to_cbor(w: &mut IndentWriter, module: &IrModule, s: &StructDef, opts: &CodegenOptions) {
    w.line("Uint8List encode() => cbor.encode(_toCborValue());");
    w.blank();
    w.line("CborValue _toCborValue() {");
    w.indent();
    w.line("final m = CborMap({");
    w.indent();
    let fields: Vec<_> = if s.dcbor {
        let mut fs: Vec<_> = s.fields.iter().collect();
        fs.sort_by(|a, b| a.name.cmp(&b.name));
        fs
    } else {
        s.fields.iter().collect()
    };
    for f in &fields {
        let fname    = dart_field(&f.name);
        let cbor_key = cbor_map_key(&f.key);
        if matches!(f.occurrence, Occurrence::Optional) {
            let val = cbor_to_expr(&f.ty, &format!("{fname}!"), module, opts);
            w.line(&format!("if ({fname} != null) {cbor_key}: {val},"));
        } else if f.occurrence.is_repeated() {
            let item_val = cbor_to_expr(&f.ty, "e", module, opts);
            w.line(&format!(
                "{cbor_key}: CborList({fname}.map((e) => {item_val}).toList()),"));
        } else {
            let val = cbor_to_expr(&f.ty, &fname, module, opts);
            w.line(&format!("{cbor_key}: {val},"));
        }
    }
    w.dedent();
    w.line("});");
    if let Some(tag) = s.tagged {
        w.line(&format!("return CborTag([{}], m);", tag.0));
    } else {
        w.line("return m;");
    }
    w.dedent();
    w.line("}");
}

// ── Enum ──────────────────────────────────────────────────────────────────────

fn emit_enum(w: &mut IndentWriter, module: &IrModule, e: &EnumDef, opts: &CodegenOptions) {
    if let Some(doc) = e.doc.as_deref() { w.line(&format!("/// {doc}")); }
    if e.deprecated { w.line("@Deprecated('deprecated in schema')"); }

    let class_name = to_pascal_case(&e.name);

    // Represent as a class with a kind string and optional value.
    // This tagged-union approach covers both homogeneous and mixed-type variants.
    w.line(&format!("class {class_name} {{"));
    w.indent();
    w.line("final String kind;");
    w.line("final Object? value;");
    w.blank();
    w.line(&format!("const {class_name}._(this.kind, [this.value]);"));
    w.blank();

    // Named constructors for each variant
    for v in &e.variants {
        let vname    = to_pascal_case(&v.name);
        let kind_str = variant_kind_str(&v.name);
        match &v.ty {
            TypeRef::Primitive(Primitive::Null | Primitive::Tstr) => {
                w.line(&format!(
                    "static const {vname} = {class_name}._({kind_str:?});"));
            }
            TypeRef::Primitive(Primitive::Uint | Primitive::Int) => {
                // Variant name encodes the literal (e.g. Variant3 → literal 3)
                if let Some(lit) = variant_int_literal(&v.name) {
                    w.line(&format!(
                        "static const {vname} = {class_name}._({kind_str:?}, {lit});"));
                } else {
                    let dart_t = primitive_to_dart(unwrap_primitive(&v.ty));
                    w.line(&format!(
                        "static {class_name} {vname}({dart_t} value) => \
                         {class_name}._({kind_str:?}, value);"));
                }
            }
            TypeRef::Primitive(_) => {
                let dart_t = primitive_to_dart(unwrap_primitive(&v.ty));
                w.line(&format!(
                    "static {class_name} {vname}({dart_t} value) => \
                     {class_name}._({kind_str:?}, value);"));
            }
            TypeRef::Named(n) => {
                let ct = to_pascal_case(n);
                w.line(&format!(
                    "static {class_name} {vname}({ct} value) => \
                     {class_name}._({kind_str:?}, value);"));
            }
            _ => {
                w.line(&format!(
                    "static const {vname} = {class_name}._({kind_str:?});"));
            }
        }
    }
    w.blank();

    if opts.is_json() {
        emit_enum_json(w, e, &class_name, opts);
    } else {
        emit_enum_cbor(w, module, e, &class_name, opts);
    }

    w.dedent();
    w.line("}");
}

fn emit_enum_json(w: &mut IndentWriter, e: &EnumDef, class_name: &str, _opts: &CodegenOptions) {
    w.line("String encode() => jsonEncode(toJson());");
    w.blank();
    w.line("dynamic toJson() {");
    w.indent();
    w.line("switch (kind) {");
    w.indent();
    for v in &e.variants {
        let kind_str = variant_kind_str(&v.name);
        let case_val = match &v.ty {
            TypeRef::Primitive(Primitive::Null | Primitive::Tstr) => {
                format!("return {kind_str:?};")
            }
            TypeRef::Primitive(Primitive::Uint | Primitive::Int) => {
                if let Some(lit) = variant_int_literal(&v.name) {
                    format!("return {lit};")
                } else {
                    "return value;".to_owned()
                }
            }
            TypeRef::Primitive(_) => "return value;".to_owned(),
            TypeRef::Named(_)     => "return (value as dynamic).toJson();".to_owned(),
            _                     => format!("return {kind_str:?};"),
        };
        w.line(&format!("case {kind_str:?}: {case_val}"));
    }
    w.dedent();
    w.line("}");
    w.line("throw StateError('Unknown kind: $kind');");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!(
        "static {class_name} decode(String s) => fromJson(jsonDecode(s));"));
    w.blank();
    w.line(&format!("static {class_name} fromJson(dynamic raw) {{"));
    w.indent();

    // String variants
    let has_str = e.variants.iter().any(|v|
        matches!(&v.ty, TypeRef::Primitive(Primitive::Null | Primitive::Tstr)));
    if has_str {
        w.line("if (raw is String) {");
        w.indent();
        w.line("switch (raw) {");
        w.indent();
        for v in &e.variants {
            if matches!(&v.ty, TypeRef::Primitive(Primitive::Null | Primitive::Tstr)) {
                let kind_str = variant_kind_str(&v.name);
                let vname    = to_pascal_case(&v.name);
                w.line(&format!("case {kind_str:?}: return {class_name}.{vname};"));
            }
        }
        w.line(&format!(
            "default: throw ArgumentError('Unknown {class_name}: $raw');"));
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
    }

    // Integer variants — match specific literal values when known
    let int_variants: Vec<_> = e.variants.iter()
        .filter(|v| matches!(&v.ty, TypeRef::Primitive(Primitive::Uint | Primitive::Int)))
        .collect();
    if !int_variants.is_empty() {
        w.line("if (raw is num) {");
        w.indent();
        let all_literals = int_variants.iter()
            .all(|v| variant_int_literal(&v.name).is_some());
        if all_literals {
            w.line("switch (raw.toInt()) {");
            w.indent();
            for v in &int_variants {
                let lit   = variant_int_literal(&v.name).unwrap();
                let vname = to_pascal_case(&v.name);
                w.line(&format!("case {lit}: return {class_name}.{vname};"));
            }
            w.line(&format!(
                "default: throw ArgumentError('Unknown {class_name}: $raw');"));
            w.dedent();
            w.line("}");
        } else {
            let vname = to_pascal_case(&int_variants[0].name);
            w.line(&format!("return {class_name}.{vname}(raw.toInt());"));
        }
        w.dedent();
        w.line("}");
    }

    // Float variants
    let float_variants: Vec<_> = e.variants.iter()
        .filter(|v| matches!(&v.ty,
            TypeRef::Primitive(
                Primitive::Float | Primitive::Float16 |
                Primitive::Float32 | Primitive::Float64)))
        .collect();
    if !float_variants.is_empty() {
        w.line("if (raw is num) {");
        w.indent();
        let vname = to_pascal_case(&float_variants[0].name);
        w.line(&format!("return {class_name}.{vname}(raw.toDouble());"));
        w.dedent();
        w.line("}");
    }

    w.line(&format!("throw ArgumentError('Cannot decode {class_name}: $raw');"));
    w.dedent();
    w.line("}");
}

fn emit_enum_cbor(w: &mut IndentWriter, module: &IrModule, e: &EnumDef, class_name: &str, opts: &CodegenOptions) {
    w.line("Uint8List encode() => cbor.encode(_toCborValue());");
    w.blank();
    w.line("CborValue _toCborValue() {");
    w.indent();
    w.line("switch (kind) {");
    w.indent();
    for v in &e.variants {
        let kind_str = variant_kind_str(&v.name);
        let cbor_val = match &v.ty {
            TypeRef::Primitive(Primitive::Null | Primitive::Tstr) => {
                format!("CborString({kind_str:?})")
            }
            TypeRef::Primitive(Primitive::Uint | Primitive::Int) => {
                if let Some(lit) = variant_int_literal(&v.name) {
                    format!("CborSmallInt({lit})")
                } else {
                    cbor_to_expr(
                        &TypeRef::Primitive(Primitive::Int), "value as int", module, opts)
                }
            }
            TypeRef::Primitive(p) => {
                cbor_to_expr(&TypeRef::Primitive(p.clone()), "value as dynamic", module, opts)
            }
            TypeRef::Named(_) => "(value as dynamic)._toCborValue()".to_owned(),
            _                 => format!("CborString({kind_str:?})"),
        };
        w.line(&format!("case {kind_str:?}: return {cbor_val};"));
    }
    w.dedent();
    w.line("}");
    if let Some(tag) = e.tagged {
        w.line(&format!("return CborTag([{}], CborNull());", tag.0));
    } else {
        w.line("throw StateError('Unknown kind: $kind');");
    }
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("static {class_name} decode(Uint8List bytes) {{"));
    w.indent();
    w.line("var v = cbor.decode(bytes);");
    if e.tagged.is_some() {
        w.line("if (v is CborTag) v = v.value;");
    }
    w.line(&format!("return {class_name}._fromCborValue(v);"));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("static {class_name} _fromCborValue(CborValue v) {{"));
    w.indent();

    // String variants
    let has_str = e.variants.iter().any(|v|
        matches!(&v.ty, TypeRef::Primitive(Primitive::Null | Primitive::Tstr)));
    if has_str {
        w.line("if (v is CborString) {");
        w.indent();
        w.line("switch (v.toString()) {");
        w.indent();
        for v2 in &e.variants {
            if matches!(&v2.ty, TypeRef::Primitive(Primitive::Null | Primitive::Tstr)) {
                let kind_str = variant_kind_str(&v2.name);
                let vname    = to_pascal_case(&v2.name);
                w.line(&format!("case {kind_str:?}: return {class_name}.{vname};"));
            }
        }
        w.line(&format!(
            "default: throw ArgumentError('Unknown {class_name}: $v');"));
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
    }

    // Integer variants
    let int_variants: Vec<_> = e.variants.iter()
        .filter(|v| matches!(&v.ty, TypeRef::Primitive(Primitive::Uint | Primitive::Int)))
        .collect();
    if !int_variants.is_empty() {
        w.line("if (v is CborInt) {");
        w.indent();
        let all_literals = int_variants.iter()
            .all(|v2| variant_int_literal(&v2.name).is_some());
        if all_literals {
            w.line("switch (v.toInt()) {");
            w.indent();
            for v2 in &int_variants {
                let lit   = variant_int_literal(&v2.name).unwrap();
                let vname = to_pascal_case(&v2.name);
                w.line(&format!("case {lit}: return {class_name}.{vname};"));
            }
            w.line(&format!(
                "default: throw ArgumentError('Unknown {class_name}: $v');"));
            w.dedent();
            w.line("}");
        } else {
            let vname = to_pascal_case(&int_variants[0].name);
            w.line(&format!("return {class_name}.{vname}(v.toInt());"));
        }
        w.dedent();
        w.line("}");
    }

    w.line(&format!("throw ArgumentError('Cannot decode {class_name}: $v');"));
    w.dedent();
    w.line("}");
}

// ── Array ─────────────────────────────────────────────────────────────────────

fn emit_array(w: &mut IndentWriter, a: &ArrayDef, opts: &CodegenOptions) {
    if let Some(doc) = a.doc.as_deref() { w.line(&format!("/// {doc}")); }
    let class_name = to_pascal_case(&a.name);
    let elem_type  = typeref_to_dart(&a.element, opts);
    // Emit a typedef alias for the list type
    w.line(&format!("typedef {class_name} = List<{elem_type}>;"));
}

// ── Map ───────────────────────────────────────────────────────────────────────

fn emit_map(w: &mut IndentWriter, m: &MapDef, opts: &CodegenOptions) {
    if let Some(doc) = m.doc.as_deref() { w.line(&format!("/// {doc}")); }
    let class_name = to_pascal_case(&m.name);
    let key_type   = typeref_to_dart(&m.key_ty, opts);
    let val_type   = typeref_to_dart(&m.val_ty, opts);
    w.line(&format!("typedef {class_name} = Map<{key_type}, {val_type}>;"));
}

// ── Alias ─────────────────────────────────────────────────────────────────────

fn emit_alias(w: &mut IndentWriter, a: &AliasDef, opts: &CodegenOptions) {
    if let Some(doc) = a.doc.as_deref() { w.line(&format!("/// {doc}")); }
    let class_name = to_pascal_case(&a.name);
    let dart_type  = typeref_to_dart(&a.ty, opts);
    w.line(&format!("typedef {class_name} = {dart_type};"));
}

// ── Test file ─────────────────────────────────────────────────────────────────

fn emit_tests(module: &IrModule, lib_name: &str, opts: &CodegenOptions) -> String {
    let mut w = IndentWriter::new(2);
    w.line("// Generated by cddlc — do not edit.");
    w.blank();

    if opts.is_json() {
        w.line("import 'dart:convert';");
    } else {
        w.line("import 'dart:typed_data';");
    }
    w.line("import 'package:test/test.dart';");
    w.line(&format!("import '../lib/{lib_name}.dart';"));
    w.blank();
    w.line("void main() {");
    w.indent();
    w.line(&format!("group('{lib_name}', () {{"));
    w.indent();

    for (_, def) in &module.types {
        if let TypeDef::Struct(s) = def {
            emit_struct_test(&mut w, s, opts);
        }
        if let TypeDef::Enum(e) = def {
            emit_enum_test(&mut w, e, opts);
        }
    }

    w.dedent();
    w.line("});");
    w.dedent();
    w.line("}");

    w.finish()
}

fn emit_struct_test(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    let class_name = to_pascal_case(&s.name);

    // Skip structs that can't be trivially default-constructed in the test
    let skip = s.fields.iter().any(|f| {
        f.occurrence.is_repeated()
            || (!matches!(f.occurrence, Occurrence::Optional)
                && matches!(&f.ty, TypeRef::Named(_) | TypeRef::Choice(_)))
    });
    if skip { return; }

    w.line(&format!("test('{class_name} roundtrip', () {{"));
    w.indent();

    // Build constructor call
    w.line(&format!("final obj = {class_name}("));
    w.indent();
    for f in &s.fields {
        let fname   = dart_field(&f.name);
        let default = test_default_for(&f.ty, &f.occurrence, opts);
        w.line(&format!("{fname}: {default},"));
    }
    w.dedent();
    w.line(");");

    if opts.is_json() {
        w.line("final encoded = obj.encode();");
        w.line(&format!("final decoded = {class_name}.decode(encoded);"));
    } else {
        w.line("final encoded = obj.encode();");
        w.line("expect(encoded, isA<Uint8List>());");
        w.line(&format!("final decoded = {class_name}.decode(encoded);"));
    }

    for f in &s.fields {
        if matches!(f.occurrence, Occurrence::Optional) { continue; }
        let fname = dart_field(&f.name);
        w.line(&format!("expect(decoded.{fname}, equals(obj.{fname}));"));
    }

    w.dedent();
    w.line("});");
}

fn emit_enum_test(w: &mut IndentWriter, e: &EnumDef, opts: &CodegenOptions) {
    let class_name = to_pascal_case(&e.name);
    // Test the first string-like variant
    let first_str = e.variants.iter().find(|v|
        matches!(&v.ty, TypeRef::Primitive(Primitive::Tstr | Primitive::Null)));
    if let Some(v) = first_str {
        let vname = to_pascal_case(&v.name);
        w.line(&format!("test('{class_name} roundtrip', () {{"));
        w.indent();
        w.line(&format!("final obj = {class_name}.{vname};"));
        if opts.is_json() {
            w.line("final encoded = obj.encode();");
            w.line(&format!("final decoded = {class_name}.decode(encoded);"));
        } else {
            w.line("final encoded = obj.encode();");
            w.line(&format!("final decoded = {class_name}.decode(encoded);"));
        }
        w.line("expect(decoded.kind, equals(obj.kind));");
        w.dedent();
        w.line("});");
    }
}

// ── Type helpers ──────────────────────────────────────────────────────────────

fn primitive_to_dart(p: &Primitive) -> &'static str {
    match p {
        Primitive::Bool                                           => "bool",
        Primitive::Null                                           => "Null",
        Primitive::Undefined                                      => "dynamic",
        Primitive::Uint | Primitive::Int                          => "int",
        Primitive::Float16 | Primitive::Float32
            | Primitive::Float64 | Primitive::Float              => "double",
        Primitive::Bstr                                           => "Uint8List",
        Primitive::Tstr                                           => "String",
        Primitive::Any                                            => "dynamic",
    }
}

fn typeref_to_dart(tr: &TypeRef, _opts: &CodegenOptions) -> String {
    match tr {
        TypeRef::Primitive(p)     => primitive_to_dart(p).to_owned(),
        TypeRef::Named(n)         => to_pascal_case(n),
        TypeRef::Tagged(_, inner) => typeref_to_dart(inner, _opts),
        TypeRef::Choice(_)        => "dynamic".to_owned(),
    }
}

fn dart_field_type(tr: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    let base = if occ.is_repeated() {
        format!("List<{}>", typeref_to_dart(tr, opts))
    } else {
        typeref_to_dart(tr, opts)
    };
    if matches!(occ, Occurrence::Optional) {
        format!("{base}?")
    } else {
        base
    }
}

fn unwrap_primitive(tr: &TypeRef) -> &Primitive {
    match tr {
        TypeRef::Primitive(p) => p,
        _                     => &Primitive::Any,
    }
}

// ── JSON helpers ──────────────────────────────────────────────────────────────

fn json_from_expr(ty: &TypeRef, expr: &str, module: &IrModule, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p) => match p {
            Primitive::Bool                   => format!("{expr} as bool"),
            Primitive::Null                   => "null".to_owned(),
            Primitive::Uint | Primitive::Int  => format!("({expr} as num).toInt()"),
            Primitive::Float16 | Primitive::Float32
                | Primitive::Float64 | Primitive::Float
                                              => format!("({expr} as num).toDouble()"),
            Primitive::Bstr                   => format!("base64Decode({expr} as String)"),
            Primitive::Tstr                   => format!("{expr} as String"),
            Primitive::Undefined | Primitive::Any => expr.to_owned(),
        },
        TypeRef::Named(n) => {
            // Resolve the named type to generate the correct expression
            match module.get(n.as_str()) {
                Some(TypeDef::Alias(a)) => {
                    // Transparent alias — decode as the underlying type
                    json_from_expr(&a.ty, expr, module, opts)
                }
                Some(TypeDef::Array(a)) => {
                    // typedef List<T> — inline list decoding
                    let item = json_from_expr(&a.element, "e", module, opts);
                    if item == "e" {
                        format!("({expr} as List).cast<dynamic>()")
                    } else {
                        format!("({expr} as List).map((e) => {item}).toList()")
                    }
                }
                Some(TypeDef::Map(_)) => {
                    // typedef Map<K,V> — pass through as dynamic map
                    format!("({expr} as Map).cast()")
                }
                Some(TypeDef::Enum(_)) => {
                    // Enum class has fromJson(dynamic)
                    let cls = to_pascal_case(n);
                    format!("{cls}.fromJson({expr})")
                }
                Some(TypeDef::Struct(_)) | None => {
                    let cls = to_pascal_case(n);
                    format!("{cls}.fromJson({expr} as Map<String, dynamic>)")
                }
            }
        }
        TypeRef::Tagged(_, inner) => json_from_expr(inner, expr, module, opts),
        TypeRef::Choice(_)        => expr.to_owned(),
    }
}

fn json_to_expr(ty: &TypeRef, field: &str, module: &IrModule, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(Primitive::Bstr) => format!("base64Encode({field})"),
        TypeRef::Named(n) => {
            match module.get(n.as_str()) {
                Some(TypeDef::Alias(a)) => json_to_expr(&a.ty, field, module, opts),
                Some(TypeDef::Array(a)) => {
                    let item = json_to_expr(&a.element, "e", module, opts);
                    if item == "e" { field.to_owned() }
                    else { format!("{field}.map((e) => {item}).toList()") }
                }
                Some(TypeDef::Map(_)) => field.to_owned(),
                _ => format!("{field}.toJson()"),
            }
        }
        TypeRef::Tagged(_, inner) => json_to_expr(inner, field, module, opts),
        _                         => field.to_owned(),
    }
}

// ── CBOR helpers ──────────────────────────────────────────────────────────────

fn cbor_from_expr(ty: &TypeRef, expr: &str, module: &IrModule, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p) => match p {
            Primitive::Bool                   => format!("({expr} as CborBool).value"),
            Primitive::Null                   => "null".to_owned(),
            Primitive::Uint | Primitive::Int  => format!("({expr} as CborInt).toInt()"),
            Primitive::Float16 | Primitive::Float32
                | Primitive::Float64 | Primitive::Float
                                              => format!("({expr} as CborFloat).value"),
            Primitive::Bstr                   =>
                format!("Uint8List.fromList(({expr} as CborBytes).bytes)"),
            Primitive::Tstr                   => format!("({expr} as CborString).toString()"),
            Primitive::Undefined | Primitive::Any => expr.to_owned(),
        },
        TypeRef::Named(n) => {
            match module.get(n.as_str()) {
                Some(TypeDef::Alias(a)) => cbor_from_expr(&a.ty, expr, module, opts),
                Some(TypeDef::Array(a)) => {
                    let item = cbor_from_expr(&a.element, "e", module, opts);
                    format!("({expr} as CborList).map((e) => {item}).toList()")
                }
                Some(TypeDef::Map(_)) => format!("{expr} as Map"),
                Some(TypeDef::Enum(_)) => {
                    let cls = to_pascal_case(n);
                    format!("{cls}._fromCborValue({expr}!)")
                }
                Some(TypeDef::Struct(_)) | None => {
                    let cls = to_pascal_case(n);
                    format!("{cls}._fromCborMap({expr} as CborMap)")
                }
            }
        }
        TypeRef::Tagged(_, inner) => cbor_from_expr(inner, expr, module, opts),
        TypeRef::Choice(_)        => expr.to_owned(),
    }
}

fn cbor_to_expr(ty: &TypeRef, field: &str, module: &IrModule, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p) => match p {
            Primitive::Bool                   => format!("CborBool({field})"),
            Primitive::Null                   => "CborNull()".to_owned(),
            Primitive::Uint | Primitive::Int  => format!("CborSmallInt({field})"),
            Primitive::Float16 | Primitive::Float32
                | Primitive::Float64 | Primitive::Float
                                              => format!("CborFloat({field})"),
            Primitive::Bstr                   => format!("CborBytes({field})"),
            Primitive::Tstr                   => format!("CborString({field})"),
            Primitive::Undefined | Primitive::Any => format!("CborString({field}.toString())"),
        },
        TypeRef::Named(n) => {
            match module.get(n.as_str()) {
                Some(TypeDef::Alias(a)) => cbor_to_expr(&a.ty, field, module, opts),
                Some(TypeDef::Array(a)) => {
                    let item = cbor_to_expr(&a.element, "e", module, opts);
                    format!("CborList({field}.map((e) => {item}).toList())")
                }
                Some(TypeDef::Map(_)) => format!("CborMap({field})"),
                Some(TypeDef::Enum(_)) => format!("{field}._toCborValue()"),
                Some(TypeDef::Struct(_)) | None => format!("{field}._toCborValue()"),
            }
        }
        TypeRef::Tagged(_, inner) => cbor_to_expr(inner, field, module, opts),
        TypeRef::Choice(_)        => "CborNull()".to_owned(),
    }
}

fn cbor_map_key(key: &FieldKey) -> String {
    match key {
        FieldKey::Text(s) => format!("CborString('{s}')"),
        FieldKey::Int(n)  => format!("CborSmallInt({n})"),
        FieldKey::Uint(n) => format!("CborSmallInt({n})"),
    }
}

// ── Test default values ───────────────────────────────────────────────────────

fn test_default_for(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    if matches!(occ, Occurrence::Optional) {
        return "null".to_owned();
    }
    if occ.is_repeated() {
        return "[]".to_owned();
    }
    match ty {
        TypeRef::Primitive(p) => match p {
            Primitive::Bool                    => "false".to_owned(),
            Primitive::Null                    => "null".to_owned(),
            Primitive::Uint | Primitive::Int   => "0".to_owned(),
            Primitive::Float16 | Primitive::Float32
                | Primitive::Float64 | Primitive::Float => "0.0".to_owned(),
            Primitive::Bstr                    => {
                if opts.is_json() {
                    "Uint8List(0)".to_owned()
                } else {
                    "Uint8List(0)".to_owned()
                }
            }
            Primitive::Tstr                    => "'test'".to_owned(),
            _                                  => "null".to_owned(),
        },
        TypeRef::Named(_)          => "null".to_owned(), // can't default-construct
        TypeRef::Tagged(_, inner)  => test_default_for(inner, occ, opts),
        TypeRef::Choice(_)         => "null".to_owned(),
    }
}

// ── Name helpers ──────────────────────────────────────────────────────────────

/// Convert a CDDL name to a Dart package name (lowercase_underscores).
fn dart_pkg(s: &str) -> String {
    to_snake_case(s).to_lowercase()
}

/// Convert a CDDL field name to lowerCamelCase.
fn dart_field(s: &str) -> String {
    let pascal = to_pascal_case(s);
    let mut chars = pascal.chars();
    match chars.next() {
        None    => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + chars.as_str(),
    }
}

/// Return the wire key string for a field key (for use in JSON / CBOR string key).
fn field_key_str(key: &FieldKey) -> String {
    match key {
        FieldKey::Text(s) => s.as_str().to_owned(),
        FieldKey::Int(n)  => n.to_string(),
        FieldKey::Uint(n) => n.to_string(),
    }
}

/// The string that represents this enum variant's wire value (from its CDDL name).
fn variant_kind_str(name: &str) -> String {
    name.replace('_', "-").to_lowercase()
}

/// For integer literal variants the IR names them "Variant{n}" where n is the literal.
/// Returns the literal integer if the name matches that pattern.
fn variant_int_literal(name: &str) -> Option<i64> {
    name.strip_prefix("Variant")?.parse::<i64>().ok()
}
